import { Source_Sans_Pro } from 'next/font/google';
import './globals.css';

const sourceSansPro = Source_Sans_Pro({
    weight: ['200', '300', '400', '600', '700', '900'],
    subsets: ['latin']
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body className={sourceSansPro.className}>
                <div className='xl:w-[800px] lg:w-2/3 sm:w-4/5 mx-auto pt-4 px-4 sm:px-8'>
                    {children}
                </div>
            </body>
        </html>
    );
}
